# Secret for your global LLM provider
global:
  createLlmSecret: false
  externalSecrets:
    enabled: false
  llmSecrets:
    create: false
    secretName: "existing-llm-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml
  agentSecrets:
    create: false

# Agent specific secrets
agent-argocd:
  agentSecrets:
    secretName: "existing-argocd-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-pagerduty:
  agentSecrets:
    secretName: "existing-pagerduty-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-github:
  agentSecrets:
    secretName: "existing-github-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-atlassian:
  agentSecrets:
    secretName: "existing-atlassian-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-backstage:
  agentSecrets:
    secretName: "existing-backstage-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-slack:
  agentSecrets:
    secretName: "existing-slack-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-confluence:
  agentSecrets:
    secretName: "agent-confluence-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-jira:
  agentSecrets:
    secretName: "existing-atlassian-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-aws:
  agentSecrets:
    secretName: "existing-aws-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-splunk:
  agentSecrets:
    secretName: "existing-splunk-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-webex:
  agentSecrets:
    secretName: "existing-webex-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml

agent-komodor:
  agentSecrets:
    secretName: "existing-komodor-secret" # Specify an existing Kubernetes secret name, or leave empty to auto-generate from values-secrets.yaml
